name: Allure Report

on:
  push:
    branches:
      - master  # Adjust this to your default branch name

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'   # Specify the Java version here (e.g., '11' for AdoptOpenJDK 11)
          distribution: 'adopt'  # Specify the distribution (e.g., 'adopt')

      - name: Build and Test with Maven
        run: mvn test

      - name: Install Allure Command-Line
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.14.0.zip
          unzip allure-2.14.0.zip
          export PATH=$PATH:/path/to/allure-2.14.0/bin

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Publish Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
